port:               4114
twilio_account_sid: fill-in-account-sid
twilio_auth_token:  fill-in-token

# This is used to encrypt sessions and next page URLs before serving them to
# the client.
#
# This should be a hex string that's exactly 64 bytes long. For example:
#
#   d7211b215341871968869dontusethisc0ff1789fc88e0ac6e296ba36703edf8
#
# Don't reuse that key - you can generate a random key by running:
#
#   openssl rand -hex 32
#
# If no secret key is present, we'll generate one when the server starts.
# However, this means that sessions and any in-progress paging attempts will
# error when the server restarts.
#
# If a server key is present, but invalid, the server will not start.
secret_key: fill-in-key

# Set to "prod" in production. See bin/serve for an example.
realm: local

# What timezone should we display for dates in the UI?
default_timezone: America/Los_Angeles

# What timezones should users be able to choose from? Defaults to the four US
# timezones.
#
# A list of valid timezones can be found here:
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#
# Note, your server may not contain exactly that same list in its
# timezone database.
timezones:
  - Asia/Singapore
  - Asia/Tokyo
  - Europe/London
  - America/New_York
  - Africa/Cairo

# What users type in their browser to reach your site
public_host: localhost:4114

# How many messages/calls to fetch per page. The larger the number, the slower
# the response. Maximum 1000. Defaults to 50.
page_size: 100

# Don't show resources that are older than this age. Valid values for this
# field are defined here: https://golang.org/pkg/time/#ParseDuration. Defaults
# to "all resources are viewable."
#
# If a user/group has a max_resource_age configured, that will override
# any value provided here.
max_resource_age: 720h

# Set this to false and users will see a "Click to view MMS" button on message
# instance pages, instead of seeing the photo on page load.
show_media_by_default: true

# This is shown as a "Contact Me" message on 401/403/404/500 error pages.
email_address: test@example.com

# Configure an error reporter. The only currently supported reporter is Sentry;
# leave empty or omit to disable error handling.
#
# You can define and register your own
# ErrorReporter as long as it uses this interface:
# https://godoc.org/github.com/saintpete/logrole/services#ErrorReporter. See
# services/error_reporter.go for an example.
#
# 500 server errors and panics are always logged to stderr.
error_reporter: sentry
error_reporter_token: your_sentry_dsn

# Which auth_scheme should we use? Valid values are "noop", "basic", or
# "google".
#
# For more on authentication, see
# https://github.com/saintpete/logrole/blob/master/docs/settings.md#authentication
auth_scheme: google

# Uncomment these fields to use basic auth with a single user and password.
#auth_scheme: basic
#basic_auth_user:     test
#basic_auth_password: hymanrickover

# To create/configure Google credentials, see
# https://github.com/saintpete/logrole/blob/master/docs/google.md
google_client_id:     customdomain.apps.googleusercontent.com
google_client_secret: W-secretkey

# Email domains that are permissible for Google authentication. Must be an
# exact match.
google_allowed_domains:
  - example.com
  - example.org
  - example.net

# Specify a policy to define groups with different permissions.
#
# Any omitted permissions are set to True. A list of valid settings for a
# user can be found on the UserSettings struct. Users cannot be part of two
# different groups.
#
# For more on the exact details of policy, see the authentication docs:
# https://github.com/saintpete/logrole/blob/master/docs/settings.md#authentication
policy:
    - name: support
      permissions:
          can_view_num_media: false
          can_view_calls: false
      users:
          - test@example.com
          - test@example.net

    - name: eng
      permissions:
          can_view_num_media: True
          can_view_calls: True
      users:
          - eng@example.com
          - eng@example.net

# Alternatively, you can load permissions from a separate file, using the same
# structure. It's not allowed to define both "policy" and "policy_file" in the
# same configuration.
# policy_file: /path/to/permission.yml
